from enum import IntEnum

class JobRoleEnum(IntEnum):
    SALES_EXECUTIVE = 0
    RESEARCH_SCIENTIST = 1
    LABORATORY_TECHNICIAN = 2
    MANUFACTURING_DIRECTOR = 3
    HEALTHCARE_REPRESENTATIVE = 4
    MANAGER = 5
    SALES_REPRESENTATIVE = 6
    RESEARCH_DIRECTOR = 7
    HUMAN_RESOURCES = 8