from enum import IntEnum

class JobRoleEnum(IntEnum):
    HUMAN_RESOURCES = 0
    LABORATORY_TECHNICIAN = 1
    MANAGER = 2
    MANUFACTURING_DIRECTOR = 3
    RESEARCH_DIRECTOR = 4
    RESEARCH_SCIENTIST = 5
    SALES_EXECUTIVE = 6
    SALES_REPRESENTATIVE = 7